### ISSUE TITLE
Welche publication objects können eine URN erhalten?

### ISSUE THREAD

**Issue by kadowa** [kadowa/omp-dnb-urn-plugin#5]
Z.z.
- monograph
- publication format

**Comment by kadowa** [comment]
Aus der _Policy für die Vergabe von URNs im Namensraum urn:nbn:de_ (http://d-nb.info/1029114455/34)

> Eine URN im Namensraum urn:nbn:de kann für ein Dokument in verschiedenen Formaten vergeben werden. (Beispiele: ein Artikel wird sowohl als html- als auch als PDF-Dokument veröffentlicht; oder ein Digitalisat wird als TIFF, jpeg, und PDF mit ergänzenden XML-Daten bereitgestellt; siehe auch unten zu Objektart „Digitalisate“). In diesen Fällen wird davon ausgegangen, dass durch mindestens eine der verschiedenen Formatarten die Langzeitarchivierung und damit die Persistenz sichergestellt wird. Die anderen Formate können als zusätzlicher Service unter der entsprechenden URN verzeichnet und angeboten werden.

Für OMP hieße das:
- Vergabe von URNs nur für _published monographs_.
- Meldung von URN-URL-Pärchen für jeden _published monograph_ via Epicur, wobei die URL der Katalogseite entspricht (s. https://github.com/kadowa/omp-xepicur-oai-plugin/issues/1).
- Falls wir für die Langzeitarchivierung via XMetaDissPlus bei der Entsprechung _record_ => _publication format_ bleiben (s. https://github.com/kadowa/omp-xmdp-metadata-plugin/issues/1), steht bei verschiedenen _publication formats_ desselben _monographs_ dieselbe URN.

Wie siehst du das, @lmaylein?

**Comment by kadowa** [comment]
Zu Kapiteln gibt es übrigens auch eindeutige Angaben:

> Es wird pro monografische Online-Publikation eine urn:nbn:de vergeben. Die Publikation wird als eine Einheit verstanden, auch wenn diese zum Teil in Kapitel unterteilt veröffentlicht ist.

**Comment by lmaylein** [comment]
Ich denke, wir müssen hier zwischen Epicur und XMetaDissPlus unterscheiden. Bei Epicur verweisen wir dann auf jeden Fall nur auf die Frontdoor von der aus alle Formate abrufbar sind.
Bei xMetaDissPlus müssen wir noch die Antwort der DNB abwarten. Im Zweifelsfall läuft es da auf die container-Datei raus, auf die dann verwiesen wird. Wenn wir hier unterschiedliche Abrufe für die verschiedenen Formate machen, wird es in der Tat so sein, dass dann bei den verschiedenen Formaten die gleiche URN (für das Dokument aus inhaltlicher Sicht) geliefert wird.

**Comment by lmaylein** [comment]
Zu den Kapitel: Ich habe dazu mal eine Frage an DNB geschickt. Ich würde das zumindest bei
Sammelbänden eher analog zu den Zeitschriftenaufsätzen sehen.

**Comment by kadowa** [comment]
Ich bin gerade noch auf ein möglicherweise gravierendes Problem gestoßen: Die OMP-OAI-Schnittstelle liefert standardmäßig einen Record für jedes Format aus; unabhängig davon, ob das gelieferte Metadatenschema für Monographien oder Formate definiert ist. So wie es aussieht, gibt es keine Möglichkeit, auf Plugin-Ebene einzustellen, dass nur für jede Monographie ein Record erstellt wird. Ich bin gerade dabei auszuloten, wie tief der Eingriff in OMP sein müsste, um das umzusetzen.

**Comment by kadowa** [comment]
URNs können jetzt zunächst nur für Monographien vergeben werden. Das Problem bei der Auslieferung wird hier angegangen: https://github.com/kadowa/omp-xmdp-oai-plugin/issues/3
